### ISSUE TITLE
Rebuild the Exit Survey application for BC Stats to support automation processes and improve administrative functionality

### ISSUE THREAD

**Issue by bcdevex** [bcgov/ExitSurveyAdmin#1]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-rebuild-the-exit-survey-application-to-improve-functionality"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-rebuild-the-exit-survey-application-to-improve-functionality">visit the opportunity page</a>.
The opportunity closes on <b>Tuesday, November 5th, 2019 at 16:00 PST</b>.</p>

**Comment by lxcor** [comment]
Hi There, Could you provide additional information related to the following requirement:

- Allow BC Stats staff to modify business rules/logic in the system and run standard and ad hoc queries through an administrative interface without requiring technical support from developers or Information Services Branch (ISB/IMB) staff;

What are some examples of business rules/logic that the staff will be modifying?

**Comment by sludlow-itgroove** [comment]
Currently the PSA uploads to an Oracle database, which your application pulls from. However, in the requirements it notes that we should have experience with MongoDB, and that the application should ' Be able to support new as well as historical data that have been collected since 2006.'

Will the new/historical data still live in the Oracle database, or is the plan to migrate the data to MongoDB?

**Comment by Lauren-Ara** [comment]
Is the questionnaire created in CallWeb, or does it get created in the exit survey application?

**Comment by ppieross** [comment]
Hi everyone, 

Thank you for your interest in this opportunity and for all your great questions. 

I have received similar questions over email, so I am just going to post the same answers here, so everyone gets the same information. If you have more questions, please let me know and I will try to get to them promptly. 

•	**Are the in-scope participants, email invitations/reminders and functionality to pull info from CallWeb already part of the Exit Survey, or do they all need to be created?**
No, these functionalities already exist in the current system. The only thing is that currently the Exit Survey tool communicate directly to CallWeb, we would possibly want to explore the possibility of doing that through an API, if feasible. 
•	**Can you give an example or two of the business rules/logic that staff will be modifying?**
For example, if the composition of the in-scope participants change again in the future, we want to be able to modified that ourselves, instead of having to go through a developer. Another example would be changing the number and cadence of reminders. We should be able to make these changes easily. 
•	**Will new and historical data (from 2006 onwards) still live in the Oracle database, or is the plan to migrate the data to a MongoDB?**
We are not deeply attached to where the data is stored, what we want is a database we can query ourselves. Currently, with the data in the oracle database we have to go through our IT support every month to query the data, because we don’t have an application that can access/connect to it. We would like a system that gives us more autonomy. 
•	**Is the questionnaire created in CallWeb, or does it get created in the exit survey application?**
The questionnaire and all the administration of the survey gets created/managed through CallWeb.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by ppieross** [comment]
Thank you to everyone who submitted a proposal to our Exit Survey Application rebuild. We really appreciate all the interest this opportunity received. Overall we received 6 proposals, and based on the evaluation criteria @plot-and-scatter was the successful candidate. 

To those who submitted a proposal, we would be happy to provide feedback if you would like that. Please contact me by email at Paola.Pierossi@gov.bc.ca.
