### ISSUE TITLE
Url in browser does not stay at the correct sub path

### ISSUE THREAD

**Issue by robinwn** [bcgov/ExitSurveyAdmin#102]
The app respond at the hosted path but when hovering over eg. Task Log the url does not have the correct sub path - it's now off the root

**Comment by hangler** [comment]
@robinwn What's the setting of "homepage" in the `package.json` file?

**Comment by rwindelz** [comment]
@hangler The current build is pulling from simple-data-model branch where homepage is set to "."

**Comment by hangler** [comment]
That’s probably the issue. Ideally, this would be set to the deployment URL, as I think the out of the box build uses that for the routing. However, I realize you don’t want to depend on that! I think there’s a workaround that should pick up the URL from the env file. Will take a look.

**Comment by rwindelz** [comment]
@hangler  Is it possible to do something like: "homepage":"?env('APP_URL')?".  I don't hold out much hope for this since it appears %PUBLIC_URL% probably won't have string interpolation applied at runtime - though i'd happily be wrong.

On a second note, if it is possible to use a runtime REACT_APP_APP_URL then it wouldn't be unreasonable to drop the callback and silent renew ones in favour of using just the APP_URL appending the respective specific purpose strings.

**Comment by robinwn** [comment]
@hangler app now deployed with updated env.js - looking better - only one issue found so far.
After logging in I'm redirected to: https://<domain>/dev/exitsurvey/admin/dev/exitsurvey/admin/employees
ie, it appears to prepend APP_PATH twice when redirecting back

**Comment by hangler** [comment]
It's actually some at-this-point-legacy code. Let's see if the change I just pushed (6b45837) fixes it!

**Comment by hangler** [comment]
I think this fixed it.
