### ISSUE TITLE
State diagram of current process

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#103]
Building on #11, draw a state diagram outlining all the statuses and how employees can move between them.

**Comment by hangler** [comment]
Initial draft of state diagram [attached](https://github.com/bcgov/ExitSurveyAdmin/files/4748929/Exit.Survey.App.state.diagram-2.pdf), and available for viewing and commenting here: https://docs.google.com/drawings/d/1U4GBR3sLX8Z1VBld7iUkswEyDFrj8sVoFpS8C4W6qyQ/edit?usp=sharing

**Comment by karmour** [comment]
Thanks for completing this so quickly, Frank! It's really helpful to see it mocked up like this. :)

I have some feedback! Here are my notes:
- Interesting that the app looks at EmployeeID, ExitCount, and RecordCount right away to determine uniqueness but the telkey generation happens much later in the process. Is that to make sure that the telkey is only generated at the stage of importing the record into Callweb?
- I noticed the YES/NO tags might be reversed for a couple of the decisions, namely "Does the employee exist in the DB?" and "Is the Override Email setting set (not empty)?"
- Do we need a check for a Final Status before the decision "Are any fields different?", so that we're not updating info for records in a final status?
- When does a record go from being a "New" status to an "Active" status?
- Should the date reference in the decision "Is today more than 6 mos past EffDate?" be set to a variable such as X to indicate that this can be changed later? (We will eventually want to set it to 3 months, after this first batch of held back employees)
- The "Set employee status based on ACURRENT_STATUS" box might be misleading. The way the survey is set up, I believe we're importing the Current Status into Callweb, not exporting it out. If we make changes to Current Status within the Admin App, we would want it imported over to Callweb. 

Additionally, are there other Current Statuses that we need to account for in this model, including any set by the Admin?

That's all my feedback so far. Looking forward to discussing as a group!

Thanks.

**Comment by hangler** [comment]
Thanks for the catch on the Yes/No tags... updated those on the diagram itself and will update the attached PDF as well.

**Comment by hangler** [comment]
As to the other questions:

> Interesting that the app looks at EmployeeID, ExitCount, and RecordCount right away to determine uniqueness but the telkey generation happens much later in the process. Is that to make sure that the telkey is only generated at the stage of importing the record into Callweb?

Yes.

> Do we need a check for a Final Status before the decision "Are any fields different?", so that we're not updating info for records in a final status?

Yes, good catch.

> When does a record go from being a "New" status to an "Active" status?

"New" is considered an active status. It just means that nothing has occurred with that user yet (see answer on ACURRENT_STATUS below).

> Should the date reference in the decision "Is today more than 6 mos past EffDate?" be set to a variable such as X to indicate that this can be changed later? (We will eventually want to set it to 3 months, after this first batch of held back employees)

Yes.

> The "Set employee status based on ACURRENT_STATUS" box might be misleading. The way the survey is set up, I believe we're importing the Current Status into Callweb, not exporting it out. If we make changes to Current Status within the Admin App, we would want it imported over to Callweb.

Yes, we actually should be doing both, and you're right that that's not properly captured here. As you suggest, we need an additional PATCH to CallWeb after we've modified the status in the ESA app (either something like `NotExiting` or if the admin modifies the status). However, if I understood earlier discussions correctly, CallWeb itself will be keeping track of whether it has sent emails to users, and we probably want to grab that information from CallWeb, too. That's what I was trying to capture in the box you're referring to.

I'll hold off making any changes to the illustration directly for now, until after we've captured everyone's feedback.

Thanks!

**Comment by karmour** [comment]
Hi Frank,

Amelia and I have reviewed the remaining states, and would like to make some label changes to make them more intuitive. Can you make the following label changes:

Ineligible (other) --> Out of Scope
Expired --> Survey: Expired
Survey Complete --> Survey: Complete
Employee Declined --> Survey: Do Not Remind/Declined


Additionally, for the "Survey: Do Not Remind/Declined" status, we realized that this should be a **non-final state**, in case someone asks to not get reminded but still wants to take the survey (apparently this does happen). Can we make that change? This would mean that there would be two non-final statuses again, with Exiting and Survey: Do Not Remind/Declined. 

Thanks!

**Comment by hangler** [comment]
@karmour  Yep, no problem. Actually there would be three non-Final states, if you include "Snail Mail Sent".

**Comment by karmour** [comment]
For some reason I thought that one was dropping off for now. But it's fine to leave it - it doesn't hurt anything! :) Then yes, there would be 3 non-final statuses. Thanks for this!

**Comment by hangler** [comment]
These status changes have been made.

**Comment by karmour** [comment]
These look great! :)

**Comment by hangler** [comment]
Great! Will keep this open as I'll still do one more update to the state diagram once we've worked through all the final little tweaks.

**Comment by karmour** [comment]
Left open awaiting update to state diagram. :-)
