### ISSUE TITLE
Dealing with NULL in ExitCount

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#124]
@karmour to follow up with Allan as to what this means.

**Comment by hangler** [comment]
@karmour just as I go through these tickets and close off all the ones I can... is this still of concern?

**Comment by karmour** [comment]
Allan assured us that the NULLs we saw were just an oversight in the testing data, and that there should never be a NULL value in live data. That said, what would the app do with a record that came in with a NULL value in Exit Count? To me it would make sense to ignore/throw it out since we can't use it.

**Comment by hangler** [comment]
At the moment, if ExitCount is NULL when the CSV text is `POST`ed to the EmployeesFromCSV endpoint, an error will occur, e.g.:

```
 There were 1 employees with errors: Exceptions: Exception with candidate employee Test Test (ID: 999): System.InvalidOperationException: Inserting a row into CallWeb failed. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
[...]
```
