### ISSUE TITLE
Create shell script to kick off API

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#54]
Probably using `CURL` or similar.

**Comment by karmour** [comment]
Recap from meeting with Allan, Robin, Amelia and myself about the transitioning period with the CSV:

**Problem 1: how to avoid bringing in the ‘old’ cases to the new tool/survey?**
o	After some back and forth, we landed on the plan to have Allan O’Neill add a filter on his own script to only include cases with EFFDTs beyond Apr 1st on the go-live day feed
o	If we desired, we could remove this filter at the end of the year once 183 days have passed, as it would then be moot
o	The only implication for us is that Amelia will need to pull a list of survey non-respondents for paper mail-out prior to this so they are not marked as inactive in the old Admin tool
_o	This will require no changes to the Admin app code as a result_

**Problem 2: How to exclude those with EFFDTs beyond Apr 1st who were already pulled into – and completed – the old survey, before Allan ‘shut off’ the taps in March?**
o	Originally Allan was going to manually scope these people out, which would have the side effect of making them ineligible for the survey in the future as well
o	Robin now has a plan to do this filtering on the CSV ingestion step
_o	This will require no changes to the Admin app code as a result_

**Problem 3: How to stop the old admin tool and survey from pulling in ‘new’ entries from the new CSV?**
o	After some discussion, Robin is now planning to decommission the old scheduled task and implement his new one the day before go-live
o	Business implications are light – we would lose email functionality in the old Admin tool, but since mostly only ‘old’ cases are in the old tool, there are not many emails going out at this point anyway
_o	This will require no changes to the Admin app code as a result_

**Problem 4 – will adding a new column to the CSV potentially impact/crash the scheduled task used to get the data to the Admin tool?**
o	Robin is not sure – we will want to test this
o	After some discussion, we decided to have Allan make a manual copy of the daily feed for 4 days’ time, using the new scope and column addition, starting today
o	We can use these for testing the scheduled task – Robin is going to grab the test feeds and fool the service into thinking they are the new daily feed, and see what happens
o	These test files will also be useful to Frank for testing the new scripts and db import function, and eventually, pushing over to Callweb

**Comment by hangler** [comment]
@robinwn has done this, I presume 😄
