### ISSUE TITLE
Extract telkey constants to settings file

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#66]
Add a function to Employee to generate a telkey according to the "new" standard in the 2016 code.

**Comment by hangler** [comment]
This is now complete, but I'm wondering what the concrete need for a telkey is. It seems to have two purposes:

1. Generation of a primary key for the combination of employee ID and employee exit count (and, in the original telkey code, the effective date as well — though it seems we will be removing this component)
2. Obfuscation of the employee ID (in the CallWeb database, maybe?)

Granted that 1) is necessary, but is 2) as well? The code to generate and decode the telkey is public, after all, and it's not a proper hashing function — just some basic arithmetic. @robinwn @karmour would appreciate some feedback on this.

**Comment by robinwn** [comment]
Strictly speaking the telkey is only as unique as the data it is constructed from and as you've noted, it is not a proper hash function - just an obfuscation of the original data.  In the current survey software each survey participant is emailed a url to the survey that includes the telkey.  This is passed around in the open. (given that email is not secure by a long shot).   This is done because there is no user management used in the current survey software.  Consequently the telkey calculation functioning as a 'secret' was the method of securing the identity of the survey participant.
This goes counter to [good security practices](https://en.wikipedia.org/wiki/Security_through_obscurity).
The ExitSurveyAdmin app only needs the telkey to identify the participant with the survey service.  eg. "has participant <id> completed their survey?"

**Comment by karmour** [comment]
Even if the components are known, the actual calculation used to generate the telkeys must remain a 'secret' to ensure respondent confidentiality. Let's discuss more at our Wednesday meeting.

**Comment by hangler** [comment]
OK, sounds good. For now, before pushing my changes, I am going to make a change to the telkey generation function (I have not committed the code yet) so that it does not reflect the actually correct telkey generation but a vague facsimile of it.

**Comment by karmour** [comment]
Thank you!

**Comment by hangler** [comment]
For now, will extract these variables into a settings file.

**Comment by hangler** [comment]
This is done.
