### ISSUE TITLE
Which fields need to be editable?

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#78]
The code essentially exists to allow the admin to edit whichever exiting employee fields they want — just needs hooking up. The question is, which fields would they want to edit? Are there any that should be off-limits? Or should they just be able to add comments and update the employee status?

**Comment by karmour** [comment]
Hi Frank, fields that I can conceive of a business case to edit include:
- email address
- physical address
- Current status (from a limited list)
- First name (to affect how we address them in communications)
- Appointment status (unlikely to ever require a change, but conceivable)
- Reason (this is a maybe depending on effort required -- occasionally we do hear of people who are flagged with the wrong type of exit in the database. Changing this field would alter how we push them through the survey, so we would also have to re-initialize the entry in Callweb so the change could be pushed over and the survey started again. Would therefore need a pop-up or warning note to the analyst saying as much. Would also have to be selected from a limited list.)

I'm reluctant to add anything related to the telkey generation to the list of fields we can manipulate. I can't conceive of a (good) reason to update a telkey or related fields in the ESA because this would impact records in Callweb as well. That said, I suppose it would be useful to be able to delete a record - or mark it as an unwanted record, in case of a duplicate. I guess we could ask it removed from the PSA's daily feed and that would automatically have it updated as "Not Exiting", would it not?

**Comment by karmour** [comment]
As for the ordering/grouping of fields on the user detail page, could we make the following rearrangements:

- Remove the following variables outright (will not be used, or is misleading): Age Group, Service Group, Location Group, Leave Date, 
- Transfer the Email variable to be in the Contact group (Address, Phone), and move that whole group to be next after the Personal Info group (First Name, etc.)
- Transfer the Original Hire Date and Back Dated variables to the Departure group (Reason, Exit Count, etc.), and then move that whole group up to be next after the Contact group, above the larger bundle of Other Demographics (Classification Group, Ministry, etc.)
- Put Ministry as the first variable in the Other Demographics group, followed by Department ID, and Appointment Status. The rest can be in any old order.

Thanks!

**Comment by hangler** [comment]
@karmour What are the possible:

* Appointment statuses?
* Reasons?

Thanks!

**Comment by hangler** [comment]
* Statuses: `Regular`, `Auxiliary`
* Reasons: per https://github.com/bcgov/ExitSurveyAdmin/issues/94
