### ISSUE TITLE
What happens when an auxiliary employee drops off the CSV?

### ISSUE THREAD

**Issue by hangler** [bcgov/ExitSurveyAdmin#82]
Per our conversation yesterday, we wanted to double-check the behaviour of an auxiliary employee being removed from the PSA CSV day-to-day. Per the current design of the system they should be set to `NotExiting`. See if we can find an example of this and verify. @karmour if you know of an explicit occurrence of this, feel free to email me.

**Comment by karmour** [comment]
I don't know of any examples, but with the new survey setup we do have a rule in place with the PSA so that auxiliary employees do not show up on the daily feed until 1 week _after_ their EFFDT, to reduce the likelihood of them being on the list for a very short time before being bumped off (because of a re-hire). If that still does happen, then they should be set to the "NotExiting" status as normal. The same employee may well reappear on the list in another 1-6 months if they get to the end of their term again, and if so, that would be a new Exit and they would be eligible to be surveyed again. I would not expect an employee to be bouncing on and off the list multiple times within a short period of time (say within a month), or if this does happen, it should be a very rare occurrence.

**Comment by karmour** [comment]
Testing pending.

**Comment by karmour** [comment]
This has been tested. If they drop off the list, they are set to "Employee Not Exiting" status. If they later come back on the list with the same EmployeeID/Exit Count/Empl Rcd combo, the existing record is updated and reset to "Exiting" status, and any fields with updates are pushed. Callweb also receives the updated information. As expected. Thanks!

**Comment by hangler** [comment]
Done.
